config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'articles#index'
  # get 'tags/:tag', to: 'articles#index', as: :tag
  resources :articles do
    resources :comments, only: [:create]
  end
  resources :users,only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments

  with_options presence: true do
    validates :title
    validates :text
  end
  
  mount_uploader :image, ImageUploader
  acts_as_taggable_on :labels
  acts_as_taggable
  is_impressionable counter_cache: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

        has_many :articles
        has_many :comments
        mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :ranking
    before_action :move_index, except: [:index, :show]

  def index
    if params[:search_title]
      @articles = Article.where('title LIKE ?', "%#{params[:search_title]}%").page(params[:page]).per(9).order("created_at DESC")
      respond_to do |format|
        format.html
        format.json
      end
    else
      @articles = Article.page(params[:page]).per(9).order("created_at DESC")
    end
    
    if params[:tag_name]
      @articles = @articles.tagged_with("#{params[:tag_name]}")
    end

  end

  def show
    @article = Article.find(params[:id])
    impressionist(@article, nil, :unique => [:session_hash])
    @comments = @article.comments.includes(:user)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy if article.user_id == current_user.id
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
    unless @article.user_id == current_user.id && user_signed_in?
      redirect_to root_path
    end
  end

  def update
    article = Article.find(params[:id])
    if article.user_id == current_user.id
      article.update(article_params)
      redirect_to articles_path
    end
  end

  def ranking
    @view_rank = Article.order('impressions_count DESC').take(3)
  end

  private

  def set_user
    @user = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:text, :image, :title, :tag_list).merge(user_id: current_user.id)
  end

  def move_index
    redirect_to root_path unless user_signed_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comments_params)
    if @comment.save
      respond_to do |format|
        format.html
        format.json
      end
    else
      redirect_to article_path(params[:article.id])
    end
  end

  private
  def comments_params
    params.permit(:text, :article_id).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @articles = @user.articles.page(params[:page]).per(9).order("created_at DESC")
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if current_user == @user
      @user.update(user_params)
      redirect_to user_path(@user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:text, :name, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.haml
.left-article
  .article
    - if user_signed_in? && current_user.id == article.user_id
      .article-edit
        = link_to "編集", edit_article_path(article.id), class: "edit"
        = link_to "削除", "/articles/#{article.id}", method: :delete, class: "delete"
    -if article.image.present?
      .article__image
        = image_tag article.image.url, size: "220x200"
    -unless article.image.present?
      .article__image
        = image_tag "http://design-ec.com/d/e_others_50/l_e_others_501.png", width: "220", height: "200"
    .article__title
      - if article.title.length > 10
        = link_to "#{article.title[0,10]}...", "/articles/#{article.id}", class: "article__title_link"
      -else
        = link_to article.title, "/articles/#{article.id}", class: "article__title_link"
    .article__latest-text
      - if article.text.length > 20
        = "#{article.text[0,20]}..."
      - else
        = article.text
    .article__user-name
      = link_to article.user.name, "/users/#{article.user.id}", class: "name_link"
    .article__create-day
      = article.created_at.strftime("%Y/%m/%d %H:%M")
    .article__tags
      - article.tag_list.each do |tag|
        = link_to tag, articles_path(tag_name: tag), class: "tag_link"

app/views/articles/_comments.html.haml
.comments-data
  .comments_user-name
    = comment.user.name
  .comments_text
    = ": #{comment.text}"

app/views/articles/_header.html.haml
.header
  .header__title
    = link_to "ブログ", articles_path, class: "form"
  .header__search
    = form_with url: articles_path, class: 'display', method: :get, local: true do |f|
      .search-title
        = f.text_field :search_title, placeholder: 'タイトルを入力', class: "title-search"
        = button_tag type: 'submit', class: 'search' do
          = fa_icon 'search', class: 'icon' 
          = f.label :search_title, '検索', class: 'icon' 
  .header-right
    - unless user_signed_in?
      .header-right__sign-up{ class: 'post'}
        = link_to "サインアップ", new_user_registration_path, class: "form"
      .header-right__sign-in{ class: 'post'}
        = link_to "サインイン", user_session_path, class: "form"
    - if user_signed_in?
      .header-right__my-page{ class: 'post'}
        = link_to "マイページ", user_path(current_user), class: "form"
      .header-right__new-article{ class: 'post'}
        = link_to "投稿", new_article_path, class: "form"
      .header-right__log-out{ class: "post"}
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "form"

app/views/articles/_ranking.html.haml
- @view_rank.each.with_index(1) do |article, i|
  .ranking
    .rank
      = "#{i}位"
    .article
      - if user_signed_in? && current_user.id == article.user_id
        .article-edit
          = link_to "編集", edit_article_path(article.id), class: "edit"
          = link_to "削除", "/articles/#{article.id}", method: :delete, class: "delete"
      -if article.image.present?
        .article__image
          = image_tag article.image.url, size: "220x200"
      -unless article.image.present?
        .article__image
          = image_tag "http://design-ec.com/d/e_others_50/l_e_others_501.png", width: "220", height: "200"
      .article__title
        - if article.title.length > 10
          = link_to "#{article.title[0,10]}...", "/articles/#{article.id}", class: "article__title_link"
        -else
          = link_to article.title, "/articles/#{article.id}", class: "article__title_link"
      .article__latest-text
        - if article.text.length > 20
          = "#{article.text[0,20]}..."
        - else
          = article.text
      .article__user-name
        = link_to article.user.name, "/users/#{article.user.id}", class: "name_link"
      .article__create-day
        = article.created_at.strftime("%Y/%m/%d %H:%M")
      .article__tags
        - article.tag_list.each do |tag|
          = link_to tag, articles_path(tag_name: tag), class: "tag_link"

app/views/articles/edit.html.haml
.contents
  = render 'header'
  .create-article
    = form_with model: @article, url: "/articles/#{@article.id}", method: :patch, local: true do |f|
      .new-article__form
        .new-article__form__title
          = f.label :title, "タイトル", class: "title-name"
          = f.text_field :title, class: "title_new", placeholder: "タイトル", value: "#{@article.title}"
        .new-article__form__text
          = f.label :text, "テキスト", class: "text-name"
          = f.text_area :text, class: "text_new", placeholder: "本文", value: "#{@article.text}"
        .new-article__form__image
          = f.label :image, "画像", class: "image-name"
          = f.label :image do
            = f.file_field :image, class: "hidden",value: "#{@article.image}"
            = f.label :image, "ファイルを選択", class: "image_new"
        .new-article__form__tag
          = f.label :tag_list, "タグ", class: "tag-name"
          = f.text_field :tag_list, value: @article.tag_list.join(','), class: "tag_new", placeholder: '複数つける場合は,(半角カンマ)で区切ってください', value: "#{@article.tag_list}"
        .new-article__form__submit
          = f.submit "編集", class: "form-btn"

app/views/articles/index.html.haml
.contents
  .header
    = render 'header'
  .left-content
    .left-content__new-arrival
      🎉新着の記事🎉
    .left-content__articles
      - @articles.each do |article|
        = render 'article', article: article
  .right-content
    .right-content__ranking
      🎉PVランキング🎉
    .right-content__articles-rank
      = render 'ranking'
  .paginate
    = paginate @articles

app/views/articles/new.html.haml
.contents
  = render 'header'
  .create-article
    = form_for(@article) do |f|
      .new-article__form
        .new-article__form__title
          = f.label :title, "タイトル", class: "title-name"
          = f.text_field :title, class: "title_new", placeholder: "タイトル"
        .new-article__form__text
          = f.label :text, "テキスト", class: "text-name"
          = f.text_area :text, class: "text_new", placeholder: "本文"
        .new-article__form__image
          = f.label :image, "画像", class: "image-name"
          = f.label :image do
            = f.file_field :image, class: "hidden"
            = f.label :image, "ファイルを選択", class: "image_new"
        .new-article__form__tag
          = f.label :tag_list, "タグ", class: "tag-name"
          = f.text_field :tag_list, value: @article.tag_list.join(','), class: "tag_new", placeholder: '複数つける場合は,(半角カンマ)で区切ってください'
        .new-article__form__submit
          = f.submit "投稿", class: "form-btn"

app/views/articles/show.html.haml
.contents
  = render 'header'
  .main-article
    .main-article_title
      = @article.title
    .main-article_created
      = @article.created_at.strftime("%Y/%m/%d %H:%M")
    - if @article.image.present?
      .main-article_image
        = image_tag @article.image.url, size: "680x500"
    .main-article_text
      = @article.text
  .comment
    - if user_signed_in?
      .comment__form
        = form_with url: article_comments_path(@article.id), method: :post, id: "new-comment", local: true do |f|
          .comment__form-submit
            = f.label :comment, "コメント", class: "comment-name"
            = f.text_field :text, class: "comment-form", placeholder: "コメントする"
            = f.submit "SENT", class: "comment-submit"
    .comment__list
      %p{ class: "comment-list"} <コメント一覧 >
      - @comments.each do |comment|
        = render "comments", comment: comment

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title bloooooog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/users/edit.html.haml
.contents
  = render 'articles/header'
  .edit-contents
    = form_with model: @user, url: "/users/#{@user.id}", class: "edit", method: :patch, local: true do |f|
      .user-edit
        .user-edit_image
          = f.label :image, "画像", class: "image-name"
          = f.label :image do
            = f.file_field :image, class: "hidden"
            = f.label :image, "アバターを選択", class: "image_new"
        .user-edit_name
          = f.label :name, "名前", class: "title-name"
          = f.text_field :name, class: "title-new"
        .user-edit_text
          = f.label :text, "テキスト", class: "text-name"
          = f.text_area :text, class: "text_new", placeholder: "自己紹介"
        .user-edit_submit
          = f.submit "編集", class: "form-btn"

app/views/users/show.html.haml
.contents
  = render 'articles/header'
  .left-content
    - @articles.each do |article|
      = render 'articles/article', article: article
  .right-content
    .right-content__profile{data: {id: @user.id}}
      - if @user.image.present?
        .right-content__profile-image
          = image_tag @user.image.url, size: "100x100"
      - unless @user.image.present?
        .right-content__profile-image
          = image_tag "https://static.mercdn.net/images/member_photo_noimage_thumb.png", size: "100×100"
      .right-content__profile-name
        = @user.name
      - if @user.text.present?
        .right-content__profile-text
          = @user.text
      - unless @user.text.present?
        .right-content__profile-text
          よろしくお願いします！！
      - if user_signed_in? && current_user.id == @user.id
        .right-content__profile-edit
          = link_to "編集する", edit_user_path(@user.id)
  .paginate
    = paginate @articles